resource "yandex_lockbox_secret" "bucket_secret" {
  name                = "bucket_secret"
  description         = "Секрет для хранения ключей подключения к бакетам"
  folder_id           = data.yandex_resourcemanager_folder.folder.folder_id
}

resource "yandex_lockbox_secret_version" "bucket_secret_version_1" {

  depends_on = [
    yandex_iam_service_account_static_access_key.sa-static-key
  ]

  secret_id = yandex_lockbox_secret.bucket_secret.id

  entries {
    key        = "accessKeyId"
    text_value = yandex_iam_service_account_static_access_key.sa-static-key.access_key // explicit secret value
  }
  entries {
    key        = "secretAccessKey"
    text_value = yandex_iam_service_account_static_access_key.sa-static-key.secret_key // explicit secret value
  }

  /*entries {
    key = "secretAccessKey"
    // value generated by a command won't be visible in Terraform state
    command {
      path = "my_secret_generator.sh"
    }
  }*/
}


resource "yandex_lockbox_secret" "postgres_secret" {
  name                = "postgres_secret"
  description         = "Секрет для хранения ключей подключения к PostgresSQL"
  folder_id           = data.yandex_resourcemanager_folder.folder.folder_id
}

resource "yandex_lockbox_secret_version" "postgres_secret_version_1" {
  secret_id = yandex_lockbox_secret.postgres_secret.id

  entries {
    key        = "DBUSER"
    text_value = var.db_user // explicit secret value
  }
  entries {
    key        = "DBPASSWORD"
    text_value = var.db_password // explicit secret value
  }
  entries {
    key        = "POSTGRES_HOST"
    text_value = yandex_mdb_postgresql_cluster.postgresql.host[0].fqdn // explicit secret value
  }
  entries {
    key        = "POSTGRES_PORT"
    text_value = var.postgres_port // explicit secret value
  }
  entries {
    key        = "POSTGRES_DB"
    text_value = var.postgres_db // explicit secret value
  }
}


resource "yandex_lockbox_secret_iam_binding" "secret-viewer" {
  secret_id = yandex_lockbox_secret.postgres_secret.id
  role      = "lockbox.payloadViewer"

  members = [
    "serviceAccount:${yandex_iam_service_account.sa-serverless-container.id}",
    "serviceAccount:${yandex_iam_service_account.sa-k8s-external-secrets-operator.id}"
  ]
}

output "postgres-host" {
  value = yandex_mdb_postgresql_cluster.postgresql.host[0].fqdn
}
output "postgres-port" {
  value = var.postgres_port
}
output "postgres-user" {
  value = var.db_user
}
output "postgres-password" {
  value = var.db_password
}

output "postgres-db" {
  value = var.postgres_db
}