apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: k8s-secret
  data:
  - secretKey: DBPASSWORD
    remoteRef:
      key: eXXXXXXXXXXXXXXXXX04 # LockBox key
      property: DBPASSWORD
  - secretKey: DBUSER
    remoteRef:
      key: eeXXXXXXXXXXXXXXXXX04
      property: DBUSER
  - secretKey: POSTGRES_HOST
    remoteRef:
      key: eXXXXXXXXXXXXXXXXX04
      property: POSTGRES_HOST
  - secretKey: POSTGRES_PORT
    remoteRef:
      key: eeXXXXXXXXXXXXXXXXX04
      property: POSTGRES_PORT
  - secretKey: POSTGRES_DB
    remoteRef:
      key: eeXXXXXXXXXXXXXXXXX04
      property: POSTGRES_DB